apiVersion: v1
kind: Config
users:
- name: kubelet
clusters:
- name: local
  cluster:
     server: http://localhost:8080
contexts:
- context:
    cluster: local
    user: kubelet
  name: service-account-context
current-context: service-account-context
