apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
  name: kubernetes-insecure
  namespace: default
spec:
  clusterIP: 10.0.0.2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kubernetes-insecure
  namespace: default
subsets:
- addresses:
  - ip: ${BRIDGE_IP}
  ports:
  - port: 8080
    protocol: TCP
